# Generated by Django 5.0.7 on 2024-07-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('senesi', models.DateField()),
                ('gelen_tyr', models.CharField(blank=True, max_length=255, null=True)),
                ('gelen_haryt', models.CharField(blank=True, max_length=255, null=True)),
                ('acylan_tyr', models.CharField(blank=True, max_length=255, null=True)),
                ('cykan_haryt', models.CharField(blank=True, max_length=255, null=True)),
                ('cykman_duran_haryt', models.CharField(blank=True, max_length=255, null=True)),
                ('deklerant_algy', models.CharField(blank=True, max_length=255, null=True)),
                ('bellik', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
